nodeLinker: pnp
installStatePath: .yarn/install-state.gz
mirror:
  binaries: https://yarnpkg.com/downloads/releases/
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
  - path: .yarn/plugins/@yarnpkg/plugin-eslint.cjs
npmRegistryServer: https://registry.yarnpkg.com
pnpShebang: '#!/usr/bin/env node'
enableNetwork: true
enableColors: true
enableTimers: true

# Supported architectures configuration
supportedArchitectures:
  - 'x64' # Add the architectures you want to support
  - 'arm64'
