const Token =
  'eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJqdXl1bmcwOTAzQG5hdmVyLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNjkyNDI4Nzc5LCJleHAiOjE2OTM3NDI3Nzl9.XvK6fao9cx3Qyd2Orul9L4yOOjNhDee404uEN9fiNEUhLXIdfyQU0GviGmmkonla';
export default Token;
